-- Run this once in the Supabase SQL editor before accepting eligibility submissions.
create table if not exists public.eligibility_submissions (
  id bigint generated by default as identity primary key,
  submission_id uuid not null unique,
  full_name text not null,
  email text not null,
  phone text not null,
  profile jsonb not null default '{}'::jsonb,
  document_paths jsonb not null default '[]'::jsonb,
  assessment jsonb,
  created_at timestamptz not null default now()
);

alter table public.eligibility_submissions enable row level security;
alter table public.eligibility_submissions add column if not exists assessment jsonb;
grant usage on schema public to anon, authenticated;
grant insert on table public.eligibility_submissions to anon, authenticated;
grant usage, select on sequence public.eligibility_submissions_id_seq to anon, authenticated;

drop policy if exists "Allow anonymous eligibility submissions"
  on public.eligibility_submissions;
create policy "Allow anonymous eligibility submissions"
  on public.eligibility_submissions for insert to anon, authenticated
  with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'eligibility-documents',
  'eligibility-documents',
  false,
  10485760,
  array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','image/jpeg','image/png']
)
on conflict (id) do nothing;

drop policy if exists "Allow anonymous eligibility document uploads"
  on storage.objects;
create policy "Allow anonymous eligibility document uploads"
  on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'eligibility-documents');
