import { useState } from 'react'
import { LockKeyhole, CreditCard } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { invokePortal } from '../../lib/portalFunctions'

export default function Payments({ schedules, agreements, payments, receipts, profile, instructions }) {
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[showInstructions,setShowInstructions]=useState(false)
 const completed=agreements.filter(a=>a.status==='completed'&&a.head_signed_at&&a.student_signed_at)
 async function pay(schedule,item){setBusy(item?.id||schedule.id);setError('');try{const result=await invokePortal('create-student-payment',{schedule_id:schedule.id,installment_id:item?.id});window.location.assign(result.checkout_url)}catch(e){setError(e.message)}finally{setBusy('')}}
 async function receipt(row){setError('');const {data,error}=await supabase.storage.from('student-private-receipts').createSignedUrl(row.pdf_path,60);if(error)setError(error.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 return <div className="portal-card"><div className="portal-card-head"><div><h2>Payments & receipts</h2><p>{profile.full_name} · {profile.student_number}</p></div><CreditCard/></div>{error&&<p role="alert" className="portal-error">{error}</p>}{!completed.length?<div className="portal-empty"><LockKeyhole/><h3>Payments are locked</h3><p>Review and sign your agreement first. Payments unlock after Trinity reviews, approves and signs the final agreement.</p></div>:<><button className="portal-outline" onClick={()=>setShowInstructions(!showInstructions)}>View payment instructions</button>{showInstructions&&<p className="portal-pending">{instructions||'Use Pay now to open the secure payment provider. Never send card details by email or upload them as a document. Contact Trinity if checkout is unavailable.'}</p>}{schedules.filter(s=>completed.some(a=>a.application_id===s.application_id)).map(s=><section key={s.id} className="portal-payment-section"><h3>{completed.find(a=>a.application_id===s.application_id)?.reference_number}</h3><p>Agreed total: {s.currency} {Number(s.total_fee).toFixed(2)}</p>{[{id:'initial',label:'Initial consultancy payment',amount:s.initial_payment},...(s.payment_installments||[])].filter(i=>Number(i.amount)>0).map(item=>{const p=payments.find(p=>p.schedule_id===s.id&&p.item_key===item.id),r=receipts.find(r=>r.payment_id===p?.id);return <article className="portal-document" key={item.id}><span className="portal-doc-info"><strong>{item.label}</strong><small>{s.currency} {Number(item.amount).toFixed(2)}{item.due_at?` · Due ${item.due_at}`:''}</small><small>Payment {p?.status||'pending'}{p?.gateway_reference?` · ${p.gateway_reference}`:''}</small></span>{!['successful','refunded'].includes(p?.status)&&<button className="portal-primary" disabled={!!busy} onClick={()=>pay(s,item.id==='initial'?null:item)}>{busy===item.id||busy===s.id?'Opening…':p?.status==='processing'?'Resume checkout':'Pay now'}</button>}{r&&<button className="portal-outline" onClick={()=>receipt(r)}>Download receipt</button>}</article>})}</section>)}{!schedules.length&&<p>Trinity has not configured a payment schedule yet.</p>}</>}<p className="portal-muted">Payment status changes only after confirmation from the payment provider.</p></div>
}
