import { useState } from 'react'
import { supabase } from '../../lib/supabase'
import { agreementLabel } from '../../lib/portalLabels'

export default function StaffStudentReview({ applications, people, documents, agreements, payments, onSelect }) {
  const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[country,setCountry]=useState(''),[date,setDate]=useState('')
  const [selected,setSelected]=useState(null),[notes,setNotes]=useState([]),[ocr,setOcr]=useState([]),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const rows=applications.filter(a=>{const p=people.find(p=>p.id===a.student_id);return (!status||a.status===status)&&(!country||a.destination===country)&&(!date||a.submitted_at.slice(0,10)===date)&&[p?.full_name,p?.nic_number,p?.passport_number,p?.student_number,a.id].some(v=>(v||'').toLowerCase().includes(query.toLowerCase()))})
  async function open(app){setBusy(true);setError('');setSelected(app);setNotes([]);setOcr([]);try{
    const ids=documents.filter(d=>d.application_id===app.id).map(d=>d.id)
    const [n,o]=await Promise.all([supabase.from('application_notes').select('*').eq('application_id',app.id).order('created_at',{ascending:false}),ids.length?supabase.from('document_extractions').select('*').in('document_id',ids):Promise.resolve({data:[]})])
    if(n.error||o.error)throw n.error||o.error;setNotes(n.data||[]);setOcr(o.data||[])
  }catch(e){setError(e.message)}finally{setBusy(false)}}
  async function save(event){event.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.from('application_notes').insert({application_id:selected.id,note:note.trim()});if(error)throw error;setNote('');await open(selected)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const person=people.find(p=>p.id===selected?.student_id)
  return <div className="portal-card portal-form-card"><h2>Student review</h2><div className="portal-form-grid"><label>Search student, NIC, passport or reference<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(applications.map(a=>a.status))].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Country<select value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{[...new Set(applications.map(a=>a.destination))].map(c=><option key={c}>{c}</option>)}</select></label><label>Submitted date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{error&&<p role="alert" className="portal-error">{error}</p>}
    {rows.map(app=>{const p=people.find(p=>p.id===app.student_id),a=agreements.find(a=>a.application_id===app.id&&a.status!=='voided');return <article className="portal-application-row" key={app.id}><div><strong>{p?.full_name||'Student'}</strong><small>{p?.student_number} · {app.destination} · {app.status.replaceAll('_',' ')}</small><small>{a?agreementLabel(a.status):'Agreement not generated'} · Payments: {payments.filter(p=>p.application_id===app.id).map(p=>p.status).join(', ')||'Not started'}</small></div><button className="portal-outline" disabled={busy} onClick={()=>open(app)}>Open profile</button><button className="portal-outline" onClick={()=>onSelect(app.id)}>Review documents</button></article>})}
    {!rows.length&&<p>No students match these filters.</p>}
    {selected&&person&&<section className="portal-student-detail"><h3>{person.full_name}</h3><dl className="portal-detail-grid">{[['Student ID',person.student_number],['NIC',person.nic_number],['Passport',person.passport_number],['Date of birth',person.date_of_birth],['Address',person.residential_address],['Phone',person.phone],['Nationality',person.nationality],['Intake',selected.intake],['Institution',selected.institution]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not supplied'}</dd></div>)}</dl><h3>OCR and confirmed identity details</h3>{ocr.map(item=><div key={item.document_id} className="portal-ocr-review"><strong>{documents.find(d=>d.id===item.document_id)?.file_name}</strong><p className="portal-pending">{item.manual_review_required?'Low or unavailable OCR confidence — manual inspection required.':'OCR confidence is high. Staff verification is still required.'}</p><div className="portal-detail-grid"><div><h4>Extracted</h4><pre>{JSON.stringify(item.fields,null,2)}</pre></div><div><h4>Student-confirmed</h4><pre>{item.confirmed_fields?JSON.stringify(item.confirmed_fields,null,2):'Awaiting confirmation'}</pre></div></div></div>)}{!ocr.length&&<p>No OCR results yet.</p>}<h3>Internal staff notes</h3><form onSubmit={save}><label>Add a note<textarea required maxLength="5000" value={note} onChange={e=>setNote(e.target.value)}/></label><button className="portal-primary" disabled={busy||!note.trim()}>Save internal note</button></form>{notes.map(n=><p key={n.id}><strong>{people.find(p=>p.id===n.author_id)?.full_name||'Staff'} · {new Date(n.created_at).toLocaleString()}</strong><br/>{n.note}</p>)}</section>}
  </div>
}
